name: easycontrol
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8
  - pip
  - pip:
    # Core dependencies for FLUX
    - diffusers>=0.30.0
    - transformers>=4.40.0
    - accelerate>=0.20.0
    - safetensors>=0.3.0
    
    # BezierAdapter specific dependencies
    - scipy>=1.10.0
    - scikit-learn>=1.3.0
    - opencv-python>=4.8.0
    - pydantic>=2.0.0
    
    # Testing and development
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - ruff>=0.1.0
    - mypy>=1.0.0
    
    # Utilities
    - numpy>=1.24.0
    - pillow>=9.5.0
    - matplotlib>=3.7.0
    - tqdm>=4.65.0
    
    # Memory optimization
    - flash-attn>=2.0.0